pray more

diff --git a/.github/workflows/run_autogpt.yml b/.github/workflows/run_autogpt.yml
--- a/.github/workflows/run_autogpt.yml
+++ b/.github/workflows/run_autogpt.yml
@@ -21,25 +21,24 @@ jobs:
         
     - name: wait for openai
       run: |
-        for x in 1 2 3 4 5 6 7 9 0 1 2 3 4 5 6 7 9 0;
-        do        
-        docker-compose -f nobuilds/docker-compose.yml ps
-        docker ps  || echo ok
-        for dpid in `docker ps -q`;
-        do
-           echo $dpid;
-           docker inspect  $dpid || echo fail
-        done
-        for url in http://localhost:8080/v1/models http://127.0.0.1:8080/v1/models http://172.18.0.3:8080/v1/models http://172.18.0.2:8080/v1/models http://172.18.0.1:8080/v1/models;
-        do
-          echo $url
-          curl --verbose $url 
-        done
-        
-        echo step
-        sleep 10
-        done
-        #timeout 300 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' https://localhost:8080/v1/models)" != "200" ]]; do sleep 5; done'
+        # for x in 1 2 3 4 5 6 7 9 0 1 2 3 4 5 6 7 9 0;
+        # do        
+        # docker-compose -f nobuilds/docker-compose.yml ps
+        # docker ps  || echo ok
+        # for dpid in `docker ps -q`;
+        # do
+        #    echo $dpid;
+        #    docker inspect  $dpid || echo fail
+        # done
+        #for url in http://localhost:8080/v1/models http://127.0.0.1:8080/v1/models http://172.18.0.3:8080/v1/models http://172.18.0.2:8080/v1/models http://172.18.0.1:8080/v1/models;
+        #do
+        #  echo $url
+        #  curl --verbose $url 
+        #done
+        #echo step
+        #sleep 10
+        #done
+        timeout 300 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' http://127.0.0.1:8080/v1/models)" != "200" ]]; do sleep 5; done'
 
     - name: Autogpt
       uses: meta-introspector/agent-action@master
